## Work
alias maze="cd ~/maze"
alias maz="cd ~/maze"
alias mono="cd ~/maze/maze-monorepo"
alias mod="cd ~/maze/maze-monorepo/services/service-moderated-testing"
alias omono="code -r ~/maze/maze-monorepo"
alias omod="code -r ~/maze/maze-monorepo/services/service-moderated-testing"
alias web="cd ~/maze/maze-monorepo/apps/maze-webapp"
alias tu="tilt up"
alias pipe="cd ~/maze/maze-monorepo/services/pipecat-ai-moderator"